// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD07DTu4bgv6SWd6a-_YZeNFlRyTcPvhXM',
    appId: '1:784514615175:web:f656a2495ba62632de3522',
    messagingSenderId: '784514615175',
    projectId: 'firesp32-e32221274',
    authDomain: 'firesp32-e32221274.firebaseapp.com',
    databaseURL: 'https://firesp32-e32221274-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'firesp32-e32221274.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNZcOJ-6ZSErhkO5l2Ll68DfIv0ihx0jY',
    appId: '1:784514615175:android:9c73b59835345911de3522',
    messagingSenderId: '784514615175',
    projectId: 'firesp32-e32221274',
    databaseURL: 'https://firesp32-e32221274-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'firesp32-e32221274.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLDBCz2rICiVTKBbkc4u9fkA6EP3TMlKw',
    appId: '1:784514615175:ios:37856ae844720aa2de3522',
    messagingSenderId: '784514615175',
    projectId: 'firesp32-e32221274',
    databaseURL: 'https://firesp32-e32221274-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'firesp32-e32221274.appspot.com',
    iosBundleId: 'com.iotaquarium.iotAquarium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLDBCz2rICiVTKBbkc4u9fkA6EP3TMlKw',
    appId: '1:784514615175:ios:a895c9d8ae19fb74de3522',
    messagingSenderId: '784514615175',
    projectId: 'firesp32-e32221274',
    databaseURL: 'https://firesp32-e32221274-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'firesp32-e32221274.appspot.com',
    iosBundleId: 'com.iotaquarium.iotAquarium.RunnerTests',
  );
}
